### ISSUE TITLE
Calling :Isort erases vim marks

### ISSUE THREAD

**Issue by brookskindle** [fisadev/vim-isort#22] opened 2017-12-22 01:18 UTC
Hi Juan,

Thanks for making this plugin, it's been an amazing time saver, especially when having to refactor projects!

I've found that calling `:Isort` on a file erases the vim marks that I was using in the file, but visually selecting the imports and pressing `<ctrl>i` doesn't (unless the mark is within the range I want to sort).

**Comment by quiqueporta** [comment] 2020-10-21 14:54
Hi! 
Is this fixed? I have the same problem and select all imports is a little annoying.

Thanks for this plugin :+1:

**Comment by fisadev** [comment] 2020-10-23 13:48
Hey! At that point in 2017 I was't able to reproduce the issue. But I'll try again. In the meantime, could you share what version of vim/neovim and isort (the python package) are you using? That could help me narrowing it down :)

**Comment by quiqueporta** [comment] 2020-10-26 09:04
I'm using Vim 8.0.1453 and isort 5.5.5, with python3 of course :)

**Comment by vds2212** [comment] 2023-07-12 08:07
I have the same problem.
I'm using:
- Vim 9.0.1292
- The last version of Isort (12/07/2023)
- Windows 10

**Comment by fisadev** [comment] 2023-07-12 21:10
@vds2212 thanks for your report in this other issue: #40! With that I was able to track down the source of the problem and it's the same in both issues. I'll close this one as duplicated, because the other one has more info on how to reproduce the problem. I'll try a fix, though it will require some big changes to the plugin. I'll post more info in #40 .

**Closed** 2023-07-12 21:16 UTC

**Comment by fisadev** [comment] 2023-07-12 22:54
I've just pushed a new version! Let's hope the issues are fixed.

**Comment by vds2212** [comment] 2023-07-13 19:52
I works like a charm. It is now only deleting the marks for the lines that have been changed which is very acceptable to me. I'm in favor of closing the issue.
